### PR TITLE
Fix unknown packet ID cause crash

### LINKED ISSUE #1419: Unable to connect to 1.7.10 server
I tried to connect to a 1.7.10 server.
When I successfully connected to the server, the program crashed. 
It's the same server and game version as #1199 .But reporting errors is not the same.....

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Fix #1419

_I am doubt about ignoring unknown packet ID is a good idea... since a bad/incorrect packet palette might also cause `IndexOutOfBound`_

### CODE REVIEW

**Comment by ORelio** [comment]
Mods should not use custom packets because they can use plugin messages. If the packet ID is unknown, maybe the client has gotten out of sync and is using some random bytes as packet ID. However, if you can successfully connect to the server and continue doing things e.g. read chat messages, move around, then maybe the server indeed has custom packets.

**Comment by ReinforceZwei** [comment]
@MCwenka said this PR fixed his problem. Should we merge this into master?

**Comment by ORelio** [comment]
OK so in that case I'd say to ignore unknown packets but only if Forge support is enabled.
Non-Forge servers should not have unknown packets unless we did something wrong when defining the palette 🙂

**Comment by OverHash** [comment]
Perhaps a warn should be thrown in the console when an unknown packet was received?

**Comment by ReinforceZwei** [comment]
> OK so in that case I'd say to ignore unknown packets but only if Forge support is enabled.

Done. Please make a review again, thank you.

**Comment by ORelio** [comment]
> 
> 
> Perhaps a warn should be thrown in the console when an unknown packet was received?

@OverHash Seems like it's the case when `debugmessages` is enabled.

**Comment by Mhowser** [comment]
Will this show the unknown packet in chat? I think it would be quite useful to see the raw packet.

**Comment by ReinforceZwei** [comment]
It will show the packet ID but not the whole packet.

**Pull request merged**
