### PR TITLE
Added ToLower to player check

### PR DESCRIPTION
**Pull request by Daenges**
Added a toLower() to the check, if the Recipient is online. Otherwise the mail would not be sent, just because one letter was higher or lower.

### CODE REVIEW

**Comment by Daenges** [comment]
Oh.. on cracked servers there could be more than one way of spelling the name! Ooops my fault! =P

**Comment by ORelio** [comment]
I think you are right, I did the Lowercase thing when taking the mail, but not when delivering it. Fixing.

**Comment by Daenges** [comment]
A problem is, that I think the char combination of a premium/mojang account is unique, but on non premium servers (without verification that you bought the game) it is possible, that players can have the same name with different capitalization. Lowering the names would lead to an incompatibility to non premium servers.

**Comment by ReinforceZwei** [comment]
Actually the username are case-insensitive, regardless mojang account or offline account.

**Comment by Daenges** [comment]
Strange.. because I was able to put two accounts with the same name, but different capitalization on my local server.

**Comment by ReinforceZwei** [comment]
Maybe it's my misunderstanding of offline account, but for mojang account, I am sure it is case-insensitive.

**Comment by ORelio** [comment]
Plugins are often case insensitive so players having the same name with only capitalization change will have issues in many plugins, not just the mailer bot in minecraft console client. 😄

**Pull request closed without merging**
