### PR TITLE
Add 1.14.2 support

### PR DESCRIPTION
**Pull request by xdavidwu**
Yet another version bump for Minecraft bugfix release.
Chat support tested and worked.

### CODE REVIEW

**Comment by ORelio** [comment]
Hi, thanks for contribuding. Did you check if block IDs changed?

**Comment by xdavidwu** [comment]
No. Where can I check that?

**Comment by Pokechu22** [comment]
You could compare the values given by [data generators](https://wiki.vg/Data_Generators).  Burger can also be used to compare (but only per-version diffs are made automatically; I just now manually [generated one for 1.14.1 to 1.14.2](https://pokechu22.github.io/Burger/diff_1.14.1_1.14.2.html)).

There are no block changes, only changes to tags (which I don't believe are relevant for MCC).

**Comment by ORelio** [comment]
Thanks @Pokechu22, added a commit to mark 1.14.2 terrain as supported. Merged 😉

**Pull request merged**
