### PR TITLE
Indev

### PR DESCRIPTION
**Pull request by mobdon**

### CODE REVIEW

**Comment by ORelio** [comment]
What were you trying to do exactly?

**Comment by mobdon** [comment]
u said to try ur dev build I was trying to use it xD sorry

**Comment by ORelio** [comment]
Okay, no worries x)
Just use Git or the GitHub client.
You'll probably want to make a fork in order to contribute.

**Comment by mobdon** [comment]
but then how to u change the setting ? I'm still confused :,(

**Comment by mobdon** [comment]
new to GitHub stuff :p :,(

**Comment by ORelio** [comment]
1) Fork the project by clicking the "Fork" button on the upper-right corner of the page
2) * Clone the fork to your computer using the provided `git clone` command
3) * Checkout the Indev branch using eitheir `git checkout Indev`
4) * Then you can modify files and see changes eitheir with `git status`
5) * Create a commit with `git add <file(s)>` and `git commit -m <message>`
6) * Finally, push back the commit to GitHub: `git push origin Indev`
7) Go back to your fork's webpage, there should be a link for making a pull request
(*) _Can also be done graphically with the official GitHub client_
There are tutorial on the Internet for more advanced Git usage but that's the basics.

**Comment by mobdon** [comment]
:,( lol still cant figure it out xD

**Comment by mobdon** [comment]
ill just wait till full release cuz I'm not GitHub smart xD thanks anyways

**Comment by mobdon** [comment]
could u just throw me a premade download of the lastest invdev if not okay

**Comment by ORelio** [comment]
If you don't want to contribute you can get latest source and deb build with :
 - [Indev.zip](https://github.com/ORelio/Minecraft-Console-Client/archive/Indev.zip) (GitHub `Download ZIP` button)
 - [MinecraftClient.exe](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) (AppVeyor dev build)

**Comment by mobdon** [comment]
the zip isn't usable for me and I cant change the setting for yeyor :,(

**Comment by ORelio** [comment]
Sorry but I don't understand your problem.

**Comment by mobdon** [comment]
okay I got it working the bot will accept tp command but not normal /tell
botname send commands :/

**Comment by mobdon** [comment]
how do u change the /tell command to /msg ? i think that is my problem

**Comment by Pokechu22** [comment]
Is it unable to _receive_ the messages?  Or just unable to _send_ them?

For fixing sending, you need to edit `privatemsgscmdname` in the configuration (set it to `privatemsgscmdname=msg`).  However, for receiving, you may need to change the expression used to parse it.

Can you post an example of the output of /msg?

**Comment by mobdon** [comment]
it receives them just fine it receives them like this [BotOwner -> Bot] is
how it receives them I don't have the new settings file since I cant
package the zip I have the master file setting :/

**Comment by mobdon** [comment]
only way i could get it to work is put the new .exe in the old orginal
master folder leaving me without the new indev settings file

**Comment by Pokechu22** [comment]
> only way i could get it to work is put the new .exe in the old orginal
> master folder leaving me without the new indev settings file

That _should_ work.  However, it's supposed to automatically create the configuration file...

Here's the default configuration file (should be saved as '`MinecraftClient.ini`'):

```ini
#Minecraft Console Client v1.8.2
#Startup Config File

[Main]

#General settings
#leave blank to prompt user on startup
#Use "-" as password for offline mode

login=
password=
serverip=

#Advanced settings

language=en_GB
botowners=Player1,Player2,Player3
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash #use 'none', 'slash' or 'backslash'
splitmessagedelay=2 #seconds between each part of a long message
mcversion=auto #use 'auto' or '1.X.X' values
brandinfo=mcc #use 'mcc','vanilla', or 'none'
chatbotlogfile= #leave empty for no logfile
privatemsgscmdname=tell #used by RemoteControl bot
showsystemmessages=true #system messages for server ops
showxpbarmessages=true #messages displayed above xp bar
terrainandmovements=false #uses more ram, cpu, bandwidth
accountlist=accounts.txt
serverlist=servers.txt
playerheadicon=true
exitonfailure=false
scriptcache=true
timestamps=false

[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.

[Proxy]
enabled=false #use 'false', 'true', or 'login' for login only
type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000
username=
password=

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
#private=^([a-zA-Z0-9_]+) whispers to you: (.+)$ #vanilla example
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\\.$

#Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=600 #10 = 1s
command=/ping

[AutoRelog]
enabled=false
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=false
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini

```

(You may need to view this online to properly copy this)

**Comment by mobdon** [comment]
okay it never did create oen I had to place the new exe in the olddd matsterfile so copy and paste and try this I guesss

**Comment by mobdon** [comment]
okay its still no sending after I redid the settings :/ it receives but
wont send

**Comment by mobdon** [comment]
[Botnam -> Me] is how it receives the msgs :/

**Comment by Pokechu22** [comment]
It does look like `[BotOwner -> Me]` should be handled already without making any changes.

To check, you did edit the new configuration file to match what you needed, right?

 * Make sure that ` privatemsgscmdname` is set to `msg`
 * Make sure that the bot is enabled
 * Make sure that you added your account to the bot owners list (`botowners` in the configuration)

**Comment by ORelio** [comment]
The configuration file is generated automatically if it does not exists, of course, if there is already a configuration file it won't generate a fresh one.

Pokechu22 already answered your questions :
 - Message receiving : uncomment and update the `private` line in `[ChatFormats]`
 - Message sending : `privatemsgscmdname=msg`

**Comment by mobdon** [comment]
okay I uncommented it how what would u update it tooo

**Comment by Pokechu22** [comment]
I think that for the example you gave, it would be this:

```regex
^\[([a-zA-Z0-9_]+) \-\> me\] (.+)$
```

If that does not work (but it should), try this:

```regex
^\§6\[\§c([a-zA-Z0-9_]+)\§6 \-\> \§cme\§6\] \§r(.+)$
```

> also would a /nic that has different capitalization affect the bot ownernames?

It looks like it is capitalization-indifferent, so capitalization shouldn't be an issue.

**Comment by mobdon** [comment]
okay nether one of those are still commanding the bot it receives but still no output would color tags affect it?

**Comment by Pokechu22** [comment]
I don't think color tags should effect it (but the second option I posted should address them)

Can you post a full message as it would appear in chat, including your name and any tags?

**Comment by mobdon** [comment]
just did

**Comment by mobdon** [comment]
pvp.desteria.com is the server if u guys feel like trying on the actual sever itself

**Comment by ORelio** [comment]
Your private messages seems pretty standard.
You should not need to set a specific private chat format.
However, I guess you didn't add yourself as a bot owner so it's ignoring you.
````ini
botowners=MOBDON
````
Note @Pokechu22 : Chat format is processed after `§c` color tags have been removed ;)

**Comment by mobdon** [comment]
it will not respond to the send command thru the I have my self in owner aswell idk why its not respondin it works with the tpa command on remote that id it

**Comment by mobdon** [comment]
it is not responding still I have my self as bot owner and it respons to tpa and tpas me but respond to the other internal commands

**Comment by ORelio** [comment]
Oh, found it, it's `Me` and not `me`, that's why it doesn't work.
So take Pokechu22's regex:
````
^\[([a-zA-Z0-9_]+) \-\> me\] (.+)$
````
And use `Me` instead of `me` and it should work :)

**Comment by mobdon** [comment]
so I think I need a specific chat format since its still not responding :/

**Comment by mobdon** [comment]
okay thank uuu

**Comment by ORelio** [comment]
Use `^\[([a-zA-Z0-9_]+) \-\> Me\] (.+)$` and not `^\[([a-zA-Z0-9_]+) \-\> me\] (.+)$`

**Comment by mobdon** [comment]
still don't work with that regex :/

**Comment by mobdon** [comment]
#Minecraft Console Client v1.8.2
#Startup Config File

[Main]

#General settings
#leave blank to prompt user on startup
#Use "-" as password for offline mode

login=
password=
serverip=

#Advanced settings

language=en_GB
botowners=Mobdon,MOBDON
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash #use 'none', 'slash' or 'backslash'
splitmessagedelay=2 #seconds between each part of a long message
mcversion=auto #use 'auto' or '1.X.X' values
brandinfo=mcc #use 'mcc','vanilla', or 'none'
chatbotlogfile= #leave empty for no logfile
privatemsgscmdname=msg #used by RemoteControl bot
showsystemmessages=true #system messages for server ops
showxpbarmessages=true #messages displayed above xp bar
terrainandmovements=false #uses more ram, cpu, bandwidth
accountlist=accounts.txt
serverlist=servers.txt
playerheadicon=true
exitonfailure=false
scriptcache=true
timestamps=false

[AppVars]
#yourvar=yourvalue
#can be used in some other fields as %yourvar%
#%username% and %serverip% are reserved variables.

[Proxy]
enabled=false #use 'false', 'true', or 'login' for login only
type=HTTP #Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000
username=
password=

[ChatFormat]
builtins=true #support for handling vanilla and common message formats
#public=^<([a-zA-Z0-9_]+)> (.+)$ #uncomment and adapt if necessary
private=^\[([a-zA-Z0-9_]+) \-\> Me\] (.+)$ 
#tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\\.$

#Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=600 #10 = 1s
command=/ping

[AutoRelog]
enabled=false
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

[ChatLog]
enabled=false
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=true
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=true
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini

**Comment by ORelio** [comment]
That's `^\[([a-zA-Z0-9_]+) \-\> Me\] (.+)$` not `^[([a-zA-Z0-9_]+) -> Me] (.+)$`.

**Comment by mobdon** [comment]
it come up that way when pasted it pasted it exactly like u said it does not work :/

**Comment by Pokechu22** [comment]
He probably did type it like that - it seems like markdown outside of code formatting hid it though.  Hm.

**Comment by ORelio** [comment]
Well this regex should work so if it don't I think I'm out of solutions :sweat_smile:
As you can see below, the regex works on the sample message you provided:

regex101-pm

And your configuration file seems OK :/

**Comment by mobdon** [comment]
okay yeah that regex still doesn't respond to internal commands thru my servers msg system only responds to /tpa on my server that's how I know its still recognizing me thru remote I just wanted hangman damn ittt lol well thanks for the help

**Comment by mobdon** [comment]
the server ip is pvp.desteria.com if u wanna try bug running their msg system for ur self ;D if not I understand

**Comment by mobdon** [comment]
how would u do a public chat? and a tpa regex? seems I had to diable builtins for ur regex to work also seems the chat delay for hangman isn't enough? 

mobdonii pvp desteria com - minecraft console client 1_28_2016 11_49_03 am

**Comment by Pokechu22** [comment]
Hold on, are you messaging yourself from the same account?  That might cause an issue (though I'm not sure).

In any case, the default TPA regex should work without needing to change it.  For normal chat, I think you would want this:

```
^(?:\[[^:\[\]]+\] )*([a-zA-Z0-9_]+)(?: \[[^:\[\]]+\])*: (.+)$
```

**Comment by mobdon** [comment]
no I have alt with close to the same name mobdon and mobdonII I have to disable the chat format built in to get commands to work but then tps don't work xD so confusing

**Comment by mobdon** [comment]
it now accepted commands but it wont accept a tpa anymore and id doesn't see my account in normal chat for hang man damn this is confusing

**Comment by mobdon** [comment]
[V] [Overlord] MOBDON [Legend]: this is how it is presented

**Comment by ORelio** [comment]
Once again, the regex is working:

regex101-public

As hinted by Pokechu22 try talking from a different account set as bot owner.

**Comment by mobdon** [comment]
so is the hang man isnt responding to and of the letters xD and it doesn't use the chat delay command

**Comment by ORelio** [comment]
Did you start the game with `/msg <botname> start`?

**Comment by mobdon** [comment]
yes it hits server spam when starting and it also throw me like 2 extra bot does not know command start

**Comment by mobdon** [comment]
fixed tpa the 2 back slashes were messing it up

**Comment by ORelio** [comment]
maybe an antispam plugin mutes the bot. Check for `Sending '<xxxx>'` lines in the bot's console.

**Comment by mobdon** [comment]
no the bot say the first command then the next 2 are blocked because they are sent to faste the config delay sint working for the hangman for me alteast

**Comment by mobdon** [comment]
any way to fonfigure the hangman to be slower and also the _____ is counted as spam if u could do _,_,_,_,_ that isnt blocked mabe update hangman a bit for me? :D

**Comment by mobdon** [comment]
mobdonii pvp desteria com - minecraft console client 1_29_2016 3_46_05 am

**Comment by Pokechu22** [comment]
How are you setting the delay?  `splitmessagedelay`?  Because that setting doesn't actually effect bots that are sending multiple messages (it effects automatic splitting of one long message) - most likely, that's what's causing the issue.

Probably, a rate-limit is necessary for bots as well.

I've got no idea why it's putting "unknown command" in private messages - that doesn't make sense.

**Comment by ORelio** [comment]
Hello,

There is a conflict between `Hangman` and `Remote Control` that are both processing the command, so handman starts the game and remote control says its an unknown command.

Hangman game definitely needs some improvements so that it gets less spam-prone, indeed.

**Comment by mobdon** [comment]
okay thank you was just trying to clear things up thanks :D

**Comment by mobdon** [comment]
also could u do a add dots or commas between the underscores that would help with spam filter :p and the possible the conflict

**Comment by ORelio** [comment]
Pokechu22 added a delay between message sending, that can be configured in INI file (default: 2 seconds), so that should help. Just grab the latest dev build [on AppVeyor](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) :)

**Comment by mobdon** [comment]
no there is a filter that if u have to many reocuring it shortens it like having 5 underscored in a row auto shorten to 2

**Comment by Pokechu22** [comment]
Does separating each underscore with a space fix it?  (IE, `_ _ _ _ _ _ _ _ _ _`)?  Because I don't think replacing them with dots would fix that.

**Comment by mobdon** [comment]
both will work dots commas or spaces its just to many repeating for to long it cuts down

**Comment by mobdon** [comment]
also the bot is still not seeing me in chat and its still giving the cofliction from the send remote

**Pull request closed without merging**
