### PR TITLE
Add information about translation to README

### PR DESCRIPTION
**Pull request by ReinforceZwei**

### CODE REVIEW

**Comment by ORelio** [comment]
Looks good. Could you add a link to the list of language names so that contributors know how to name their translation files?

**Comment by ReinforceZwei** [comment]
Where should I put the full language list? The list on MS Docs was cut.

**Comment by ReinforceZwei** [comment]
The language names of the translation file should follow the `CULTURE` column in the below list. For Chinese, please use the legacy one. (`zh-CHS` and `zh-CHT`)
```
CULTURE ISO ISO WIN DISPLAYNAME                              ENGLISHNAME
        iv  IVL IVL Invariant Language (Invariant Country)   Invariant Language (Invariant Country)  
ar      ar  ara ARA Arabic                                   Arabic                                  
bg      bg  bul BGR Bulgarian                                Bulgarian                               
ca      ca  cat CAT Catalan                                  Catalan                                 
zh-Hans zh  zho CHS Chinese (Simplified)                     Chinese (Simplified)                    
zh-CHS  zh  zho CHS Chinese (Simplified) Legacy              Chinese (Simplified) Legacy             
cs      cs  ces CSY Czech                                    Czech                                   
da      da  dan DAN Danish                                   Danish                                  
de      de  deu DEU German                                   German                                  
el      el  ell ELL Greek                                    Greek                                   
en      en  eng ENU English                                  English                                 
es      es  spa ESP Spanish                                  Spanish                                 
fi      fi  fin FIN Finnish                                  Finnish                                 
fr      fr  fra FRA French                                   French                                  
he      he  heb HEB Hebrew                                   Hebrew                                  
hu      hu  hun HUN Hungarian                                Hungarian                               
is      is  isl ISL Icelandic                                Icelandic                               
it      it  ita ITA Italian                                  Italian                                 
ja      ja  jpn JPN Japanese                                 Japanese                                
ko      ko  kor KOR Korean                                   Korean                                  
nl      nl  nld NLD Dutch                                    Dutch                                   
no      nb  nob NOR Norwegian                                Norwegian                               
pl      pl  pol PLK Polish                                   Polish                                  
pt      pt  por PTB Portuguese                               Portuguese                              
rm      rm  roh RMC Romansh                                  Romansh                                 
ro      ro  ron ROM Romanian                                 Romanian                                
ru      ru  rus RUS Russian                                  Russian                                 
hr      hr  hrv HRV Croatian                                 Croatian                                
sk      sk  slk SKY Slovak                                   Slovak                                  
sq      sq  sqi SQI Albanian                                 Albanian                                
sv      sv  swe SVE Swedish                                  Swedish                                 
th      th  tha THA Thai                                     Thai                                    
tr      tr  tur TRK Turkish                                  Turkish                                 
ur      ur  urd URD Urdu                                     Urdu                                    
id      id  ind IND Indonesian                               Indonesian                              
uk      uk  ukr UKR Ukrainian                                Ukrainian                               
be      be  bel BEL Belarusian                               Belarusian                              
sl      sl  slv SLV Slovenian                                Slovenian                               
et      et  est ETI Estonian                                 Estonian                                
lv      lv  lav LVI Latvian                                  Latvian                                 
lt      lt  lit LTH Lithuanian                               Lithuanian                              
tg      tg  tgk TAJ Tajik                                    Tajik                                   
fa      fa  fas FAR Persian                                  Persian                                 
vi      vi  vie VIT Vietnamese                               Vietnamese                              
hy      hy  hye HYE Armenian                                 Armenian                                
az      az  aze AZE Azerbaijani                              Azerbaijani                             
eu      eu  eus EUQ Basque                                   Basque                                  
hsb     hsb hsb HSB Upper Sorbian                            Upper Sorbian                           
mk      mk  mkd MKI Macedonian                               Macedonian                              
st      st  sot SOT Southern Sotho                           Southern Sotho                          
ts      ts  tso TSO Tsonga                                   Tsonga                                  
tn      tn  tsn TSN Tswana                                   Tswana                                  
xh      xh  xho XHO Xhosa                                    Xhosa                                   
zu      zu  zul ZUL Zulu                                     Zulu                                    
af      af  afr AFK Afrikaans                                Afrikaans                               
ka      ka  kat KAT Georgian                                 Georgian                                
fo      fo  fao FOS Faroese                                  Faroese                                 
hi      hi  hin HIN Hindi                                    Hindi                                   
mt      mt  mlt MLT Maltese                                  Maltese                                 
se      se  sme SME Northern Sami                            Northern Sami                           
ga      ga  gle IRE Irish                                    Irish                                   
ms      ms  msa MSL Malay                                    Malay                                   
kk      kk  kaz KKZ Kazakh                                   Kazakh                                  
ky      ky  kir KYR Kyrgyz                                   Kyrgyz                                  
sw      sw  swa SWK Swahili                                  Swahili                                 
tk      tk  tuk TUK Turkmen                                  Turkmen                                 
uz      uz  uzb UZB Uzbek                                    Uzbek                                   
bn      bn  ben BNG Bangla                                   Bangla                                  
pa      pa  pan PAN Punjabi                                  Punjabi                                 
gu      gu  guj GUJ Gujarati                                 Gujarati                                
or      or  ori ORI Odia                                     Odia                                    
ta      ta  tam TAI Tamil                                    Tamil                                   
te      te  tel TEL Telugu                                   Telugu                                  
kn      kn  kan KDI Kannada                                  Kannada                                 
ml      ml  mal MYM Malayalam                                Malayalam                               
as      as  asm ASM Assamese                                 Assamese                                
mr      mr  mar MAR Marathi                                  Marathi                                 
mn      mn  mon MON Mongolian                                Mongolian                               
bo      bo  bod BOB Tibetan                                  Tibetan                                 
cy      cy  cym CYM Welsh                                    Welsh                                   
km      km  khm KHM Khmer                                    Khmer                                   
lo      lo  lao LAO Lao                                      Lao                                     
my      my  mya MYA Burmese                                  Burmese                                 
gl      gl  glg GLC Galician                                 Galician                                
kok     kok kok KNK Konkani                                  Konkani                                 
si      si  sin SIN Sinhala                                  Sinhala                                 
chr     chr chr CRE Cherokee                                 Cherokee                                
am      am  amh AMH Amharic                                  Amharic                                 
tzm     tzm tzm TZA Central Atlas Tamazight                  Central Atlas Tamazight                 
ne      ne  nep NEP Nepali                                   Nepali                                  
fy      fy  fry FYN Western Frisian                          Western Frisian                         
ps      ps  pus PAS Pashto                                   Pashto                                  
fil     fil fil FPO Filipino                                 Filipino                                
ff      ff  ful FUL Fulah                                    Fulah                                   
ha      ha  hau HAU Hausa                                    Hausa                                   
yo      yo  yor YOR Yoruba                                   Yoruba                                  
nso     nso nso NSO Northern Sotho                           Northern Sotho                          
lb      lb  ltz LBX Luxembourgish                            Luxembourgish                           
kl      kl  kal KAL Kalaallisut                              Kalaallisut                             
ig      ig  ibo IBO Igbo                                     Igbo                                    
om      om  orm ORM Oromo                                    Oromo                                   
ti      ti  tir TIR Tigrinya                                 Tigrinya                                
haw     haw haw HAW Hawaiian                                 Hawaiian                                
so      so  som SOM Somali                                   Somali                                  
ii      ii  iii III Sichuan Yi                               Sichuan Yi                              
br      br  bre BRE Breton                                   Breton                                  
ug      ug  uig UIG Uyghur                                   Uyghur                                  
gsw     gsw gsw GSW Swiss German                             Swiss German                            
sah     sah sah SAH Sakha                                    Sakha                                   
rw      rw  kin KIN Kinyarwanda                              Kinyarwanda                             
gd      gd  gla GLA Scottish Gaelic                          Scottish Gaelic                         
bs-Cyrl bs  bos BSC Bosnian (Cyrillic)                       Bosnian (Cyrillic)                      
bs-Latn bs  bos BSB Bosnian (Latin)                          Bosnian (Latin)                         
sr-Cyrl sr  srp SRO Serbian (Cyrillic)                       Serbian (Cyrillic)                      
sr-Latn sr  srp SRM Serbian (Latin)                          Serbian (Latin)                         
smn     smn smn SMN Inari Sami                               Inari Sami                              
az-Cyrl az  aze AZC Azerbaijani (Cyrillic)                   Azerbaijani (Cyrillic)                  
zh      zh  zho CHS Chinese (Simplified)                     Chinese (Simplified)                    
nn      nn  nno NON Norwegian Nynorsk                        Norwegian Nynorsk                       
bs      bs  bos BSB Bosnian                                  Bosnian                                 
az-Latn az  aze AZE Azerbaijani (Latin)                      Azerbaijani (Latin)                     
uz-Cyrl uz  uzb UZC Uzbek (Cyrillic)                         Uzbek (Cyrillic)                        
mn-Cyrl mn  mon MNN Mongolian (Cyrillic)                     Mongolian (Cyrillic)                    
zh-Hant zh  zho CHT Chinese (Traditional)                    Chinese (Traditional)                   
zh-CHT  zh  zho CHT Chinese (Traditional) Legacy             Chinese (Traditional) Legacy            
nb      nb  nob NOR Norwegian Bokm?l                         Norwegian Bokm?l                        
sr      sr  srp SRB Serbian                                  Serbian                                 
tg-Cyrl tg  tgk TAJ Tajik (Cyrillic)                         Tajik (Cyrillic)                        
dsb     dsb dsb DSB Lower Sorbian                            Lower Sorbian                           
uz-Latn uz  uzb UZB Uzbek (Latin)                            Uzbek (Latin)                           
pa-Arab pa  pan PAP Punjabi (Arabic)                         Punjabi (Arabic)                        
tzm-Latn tzm tzm TZA Central Atlas Tamazight (Latin)          Central Atlas Tamazight (Latin)         
ha-Latn ha  hau HAU Hausa (Latin)                            Hausa (Latin)  
```

**Comment by ORelio** [comment]
Thanks 👍

**Pull request merged**
