### PR TITLE
Add setting for overriding attack speed for autoattack

### LINKED ISSUE #1511: How to change attack speed?
How to change attack speed? Attack Speed is low, sorry my English very bad :(

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Resolve #1511

### CODE REVIEW

**Comment by ORelio** [comment]
Hi,

How about `cooldownsecond=auto` when not set?
This way the user does not need to set `overrideattackspeed` in config:

```ini
 cooldownsecond=auto                # How long to wait between attacks in seconds, or "auto" to auto-adjust.
```
```C#
case "cooldownsecond":
    if (argValue.ToLower() == "auto")
    {
        AutoAttack_OverrideAttackSpeed = false;
    }
    else
    {
        AutoAttack_OverrideAttackSpeed = true;
        AutoAttack_CooldownSecond = str2int(argValue);
    }
    break;
````

Also, what happens if the user sets `cooldownsecond=0`?
Or a negative value? Would a minimum delay be relevant or not?

**Comment by ReinforceZwei** [comment]
> How about cooldownsecond=auto when not set?

Thanks for the nice idea :D

> Also, what happens if the user sets cooldownsecond=0?

I forgot to handle such case when implementing this last night. Now it will use `auto` if invalid value was given.

**Comment by ORelio** [comment]
I only realize it now, but there is a slight grammar issue in the variable/setting name:
usually you'd write `cooldownseconds` and `attackCooldownSeconds` with as `s`
Apart from that the code is good 😄 👍

**Comment by ReinforceZwei** [comment]
Ok, I will fix it before merging.

**Pull request merged**
