### PR TITLE
Remove local function syntax in AutoCraft

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Seems like AppVeyor do not support this syntax. [MSDocs](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions)
image

### CODE REVIEW

**Comment by ORelio** [comment]
Ah, yes. You cannot do this in C#4

**Comment by ReinforceZwei** [comment]
@ORelio The build process still fails. The problem line is `Enum.TryParse(value, out ItemType itemType)`

**Comment by ORelio** [comment]
Ah, also it's not possible to declare an `out` variable directly in method call. Fixed.

**Comment by ReinforceZwei** [comment]
Oh I see. My visual studio told me I could do that.

**Comment by ORelio** [comment]
Yes, because on newer C# versions you can do this. The project is still using C#4.0 because it's supported on older systems and Mono versions. We might migrate to .NET 5 once available since it would have a Linux runtime hopefully better than Mono.

**Comment by Mhowser** [comment]
.NET 5 is out https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by ReinforceZwei** [comment]
Isn't it a preview version? At least we should wait for the release version.

**Comment by Mhowser** [comment]
Well, it might be a good idea to start porting over to the preview versions. That way the heavy work will be done by the time .NET 5 is fully released. But I'm not a developer so I don't know.

**Comment by ORelio** [comment]
It's better to wait for it to be stable and generally available to all major operating systems. Once we migrate to it, the project won't compile and run on .NET 4 runtimes anymore so the win / lose tradeoff must be worthwhile.

**Pull request merged**
