### PR TITLE
TLS 1.2 Compatibility

### PR DESCRIPTION
**Pull request by DanielAtom**
Fix for #1780

Tested it and it works.

### CODE REVIEW

**Comment by Jaydenp11** [comment]
how do i open it i see no .exe file

**Comment by Tobi612** [comment]
Where do I paste this ".cs" and ".csproj" files into?

**Comment by Jaydenp11** [comment]
I dragged MinecraftClient.csproj into msbuild and its creating the bin folder but not the exe file

**Comment by Tobi612** [comment]
I'm sorry to ask this, but I'm really not into this, where I find "msbuild"?

**Comment by Jaydenp11** [comment]
> Where do I paste this ".cs" and ".csproj" files into?

i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file

**Comment by DanielAtom** [comment]
> > Where do I paste this ".cs" and ".csproj" files into?
> 
> i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file

wait for them to merge this into the main branch and download the compiled exe

**Comment by Tobi612** [comment]
I feel really dumb. Where is the description you mentioned?

**Comment by Jaydenp11** [comment]
Under where u find the files

**Comment by Jaydenp11** [comment]
> > > Where do I paste this ".cs" and ".csproj" files into?
> > 
> > 
> > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> 
> wait for them to merge this into the main branch and download the compiled exe

So i manually put the .exe file in the bin folder or somewhere else?

**Comment by DanielAtom** [comment]
> > > > Where do I paste this ".cs" and ".csproj" files into?
> > > 
> > > 
> > > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> > 
> > 
> > wait for them to merge this into the main branch and download the compiled exe
> 
> So i manually put the .exe file in the bin folder or somewhere else?

Wait for them to merge this pull request into the main brench. When you see "Merged" on this pull request, you can download it from the releases link.

**Comment by Jaydenp11** [comment]
> > > > > Where do I paste this ".cs" and ".csproj" files into?
> > > > 
> > > > 
> > > > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> > > 
> > > 
> > > wait for them to merge this into the main branch and download the compiled exe
> > 
> > 
> > So i manually put the .exe file in the bin folder or somewhere else?
> 
> Wait for them to merge this pull request into the main brench. When you see "Merged" on this pull request, you can download it from the releases link.

I got it to create the exe file but it still gives me the same ssl message

**Comment by DanielAtom** [comment]
> > > > > > Where do I paste this ".cs" and ".csproj" files into?
> > > > > 
> > > > > 
> > > > > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> > > > 
> > > > 
> > > > wait for them to merge this into the main branch and download the compiled exe
> > > 
> > > 
> > > So i manually put the .exe file in the bin folder or somewhere else?
> > 
> > 
> > Wait for them to merge this pull request into the main brench. When you see "Merged" on this pull request, you can download it from the releases link.
> 
> I got it to create the exe file but it still gives me the same ssl message

You probably did something wrong. Install Visual Studio

**Comment by Jaydenp11** [comment]
> > > > > > > Where do I paste this ".cs" and ".csproj" files into?
> > > > > > 
> > > > > > 
> > > > > > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> > > > > 
> > > > > 
> > > > > wait for them to merge this into the main branch and download the compiled exe
> > > > 
> > > > 
> > > > So i manually put the .exe file in the bin folder or somewhere else?
> > > 
> > > 
> > > Wait for them to merge this pull request into the main brench. When you see "Merged" on this pull request, you can download it from the releases link.
> > 
> > 
> > I got it to create the exe file but it still gives me the same ssl message
> 
> You probably did something wrong. Install Visual Studio Wait for them to merge. Please. Stop trying to compile it yourself. Wait for them to merge it to the main branch.

how tf do i merge

**Comment by Jaydenp11** [comment]
> > > > > > > > > Where do I paste this ".cs" and ".csproj" files into?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > i found the msbuild.exe on the location the description told me u just drag the csproj file on msbuild but for me its not creating the exe file
> > > > > > > 
> > > > > > > 
> > > > > > > wait for them to merge this into the main branch and download the compiled exe
> > > > > > 
> > > > > > 
> > > > > > So i manually put the .exe file in the bin folder or somewhere else?
> > > > > 
> > > > > 
> > > > > Wait for them to merge this pull request into the main brench. When you see "Merged" on this pull request, you can download it from the releases link.
> > > > 
> > > > 
> > > > I got it to create the exe file but it still gives me the same ssl message
> > > 
> > > 
> > > You probably did something wrong. Install Visual Studio Wait for them to merge. Please. Stop trying to compile it yourself. Wait for them to merge it to the main branch.
> > 
> > 
> > how tf do i merge
> 
> ORelio merges it, not you. He owns the repo. Please wait and read what I say.

it just does not work :/

**Pull request closed without merging**
