### PR TITLE
Add 1.14.3 support

### PR DESCRIPTION
**Pull request by NurdTurd**

### CODE REVIEW

**Comment by igoro00pl** [comment]
hey, i saw you added 1.14.3 support. I dont want to install Visual Studio(is that what i need to compile this?) on my computer for one compilation. Can you compile and send .exe for me?

**Comment by NurdTurd** [comment]
> hey, i saw you added 1.14.3 support. I dont want to install Visual Studio(is that what i need to compile this?) on my computer for one compilation. Can you compile and send .exe for me?

It hasn't been added into master, so no, I cannot.

**Comment by igoro00pl** [comment]
Ok so what ide can compile it? Visual Studio?

**Comment by Mhowser** [comment]
Would vscodium work? https://vscodium.com

**Comment by TNTUP** [comment]
I built MCC with SharpDevelop and it runs fine^^ Thats how I built mine after adding 1.14.3 protocol change (in a fork)

**Comment by Mjone77** [comment]
I compiled using `msbuild` and I am able to log in to 1.14.3 servers. Attached a zip containing the compiled exe.
[MinecraftClient-1.14.3.zip](https://github.com/ORelio/Minecraft-Console-Client/files/3393430/MinecraftClient-1.14.3.zip)

**Comment by ORelio** [comment]
Woops, sorry about the delay. You can now use the [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). :wink:

**Pull request merged**
