### PR TITLE
Proxy work-around / Fix.

### PR DESCRIPTION
**Pull request by ZizzyDizzyMC**
Added 'loginonlyproxy' option with true / false boolean options.
on 'true' only the minecraft login is redirected to the proxy.
Otherwise both the login and the server connection are routed though the
chosen proxy.

This was mentioned by me on Minecraftforums so I eventually pulled it off myself.  Not sure if it works 100% properly BUT it does work on my test box.  True works and false does nothing new.
Provides a semi-workaround to issues #89 and #80 on ORelio/Indev

### CODE REVIEW

**Comment by ZizzyDizzyMC** [comment]
This is here because sometimes we just use proxies to login to minecraft but don't intend to (ab)use the proxies to play minecraft.  Most proxy owners don't like this and definitely block your average minecraft port.  

Keep in mind if you can't connect to port 25565 on an outside network this doesn't help you at all.

This is an intended fix for those trying to log in a LOT of accounts using one of my scripts.  Mostly because spamming mojang servers with logins WILL result in an IP blacklist / tempban from their services.  Spreading out logins between proxies to reduce the likelihood of that happening.

NOTE: Use public proxies at your own risk. Mojang may lock your account if you try to login too many times on a proxy others have abused first.

**Comment by ORelio** [comment]
Hello,

Nice addition! The way of doing this is perfectly valid, however there are currently some issues with your pull request that needs your attention before merging:
- What is the purpose of removing `case "herochatmessagesenabled"` from `Settings.cs`?
- Did you know that `=` stands for assignation? This means that `if (Settings.LoginOnlyProxy = true)` will first assign `true` to `Settings.LoginOnlyProxy` and then check that the assignation statement's value is `true`. You should use `==` for testing a value. But as `if` expects a boolean, and `Settings.LoginOnlyProxy` _is already a boolean_, you can use: `if (Settings.LoginOnlyProxy)`

To update your pull request, just create a new commit and push it to your repository on the same branch as used for making the pull request: `Indev`

On a side note: How about using `onlyforlogin` as setting name? Since this setting can be found in `Proxy` section of the configuration file, the end user already knows this is a proxy setting, so no need to specify it again, and I think this would be more explicit, removing the need of adding a comment for explaining what is the purpose of the setting :)

**Comment by ZizzyDizzyMC** [comment]
OH CRAP OOPS LOL.  The single '=' was a mistake should be '=='.  The case "herochatmessages" was removed was a double in the config file. (How I did not catch this earlier is beyond me.) 

Making changes and re-posting soon.

**Comment by ZizzyDizzyMC** [comment]
I'm sad now and give up. The files changed themselves overnight and I clicked reload and now my build is failing. What changes were made to them?

**Comment by ORelio** [comment]
Oh, yes, you are right, that `herochatmessagesenabled` line had nothing to do there. Well, did not change anything, since all your commits were pushed you could clone again your repository and restart working from there. If you can't, I can alternatively merge the pull requests and apply the fixes myself right after merging.

**Comment by ZizzyDizzyMC** [comment]
I'm fixing it. Somehow my github client got set to where YOUR repository was MY repository and downloaded yours and overwrote mine. No reason given.

**Comment by ZizzyDizzyMC** [comment]
Done.  After some minor fiddling with github client I got I switched back to my repository only after somehow committing changes directly to your project (That's impossible right?) after the changes were committed then reverted I switched back over to my repository where I sync'd my changes back to myself and edited those working files.

**Comment by ZizzyDizzyMC** [comment]
It's ready to go. I've tested it though the weekend.

**Comment by ORelio** [comment]
Great! Merged :)

**Pull request merged**
