### PR TITLE
Implement schedule main thread task with return value

### PR DESCRIPTION
**Pull request by ReinforceZwei**
I tried my best to implement this. Unfortunately for delayed task there is no way to get the returned value or the calling thread will have to wait until the task has executed.

image

### CODE REVIEW

**Comment by ORelio** [comment]
Hi,
Of course if you want to retrieve the value you need to wait. That seems normal. And it will be useful for scripts (#1510)
You can launch the task asynchronously only if you don't care about the result 😉

**Comment by ReinforceZwei** [comment]
There is a new class `TaskWithResult` but I think the class name is not good enough to reflect the class functionality. Is there any better idea?

**Comment by ReinforceZwei** [comment]
_Oops I accidentally commited my test code._

**Comment by ORelio** [comment]
Hi, I hadn't enough time on my side to fully review this PR before it got merged (sorry), so I reworked the feature afterwards in commit c1cfaf520d04dc939376700dab5f7bbe1d743c95. Basically it works as before but with various improvements such as type handling for return value, exception handling, and suppressing the need to write `new Action()` each time we want to invoke a task on main thread. Now I'll look into making the ChatBot API thread-safe using this new mechanism. Thanks again for your contribution 😉

**Pull request merged**
