### PR TITLE
Update VKAPI

### PR DESCRIPTION
**Pull request by Nekiplay**
### Done VKAPI

- [x] KickUser
- [x] SendMessage KeyBoard (you will need to translate the generated keyboard to Json string format) I am use image
### Done
- [x] Add custom dlls

UPD №1:
To use the Keyboard
1. Add dll Newtonsoft.Json.dll
Example:
image
2. Convert class Keybord to string 
Example:
image

### CODE REVIEW

**Comment by ORelio** [comment]
Is this pull request ready for merging?

**Comment by Nekiplay** [comment]
> Is this pull request ready for merging?


70-80& yes

**Comment by ORelio** [comment]
I'm not sure there is an easy way for this in version 4.0 of .NET framework. This is not an issue for MCC itself because all JSON requests are simple so they are hardcoded [example](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs#L274). If you can, just do the same. Otherwise, it should not be _that_ difficult to add encoding to the existing JSON class but will require some work.

**Comment by Nekiplay** [comment]
hile I do not have a ready-made class for working with json, so you can not merge this request for now

**Comment by Nekiplay** [comment]
image
I was able to connect the DLL in this way

**Comment by ORelio** [comment]
Looks good! Related issue: #1154 - Please let me know if it's ready for merging.

**Comment by Nekiplay** [comment]
> Looks good! Related issue: #1154 - Please let me know if it's ready for merging.


Everything is ready.

**Pull request merged**
