### PR TITLE
Added functionality to Auto Respond Bot

### PR DESCRIPTION
**Pull request by Bancey**
Added the ability to ignore player names, enabled by default.
Stopped the bot from responding to itself, causing some issues where the
bot would infinitely loop because it was detecting something in its
response

### CODE REVIEW

**Comment by Bancey** [comment]
Removed unnecessary console output.

**Comment by ORelio** [comment]
Seems like you are trying to determinate if this is a chat message or not:
```csharp
if (text.Contains("<" + Settings.Username.ToLower() + ">"))
````
```csharp
Regex regex = new Regex(@"\<[^\)]+\>");
````
If so, please use `isPrivateMessage`, `isChatMessage`, `isValidName` and so on
These methods from the `ChatBot` API are here to make your life easier :)

**Comment by Bancey** [comment]
I'm not telling if it is a chat message or not, I'm stripping the <Player_Name> from the front of the string :)

**Comment by ORelio** [comment]
Stripping username is easier if you know that it's a chat message: `isChatMessage` also gives you the message without the username, and makes easier for the bot to ignore itself:
````csharp
//string text = the raw message

string sender = "";
string message = "";

if (isChatMessage(text, ref message, ref sender))
{
    if (sender == Settings.Username)
    {
        return; //this is a message from the bot, feel free to ignore it
    }
    else text = message; //keep only the message, removing username
}

//rest of processing
````
This way you can remove username from any supported chat message format,
eg `<**faction ~nicknamed>: message`, not only from regular `<username> message` syntax.

Plus, less code is easier to read and maintain, and copy-and-paste is not recommended. I saw a copy of `FromFile` earlier, if you think it would be useful for your bot, moving it from `Alerts.cs` to `ChatBot.cs` would make it accessible for any chatbot without needing to copy-and-paste. This way, if a modification to `FromFile` is required, there is only one copy to update :)

Apart from that, nice improvements!
Seeing the bot responding to itself would be quite hilarious ;D

**Comment by ORelio** [comment]
Manually added your changes in 00295611359e1f2773817d61770d76e380181842, thanks for your contribution!

**Pull request closed without merging**
