### PR TITLE
Clean AutoAttack

### PR DESCRIPTION
**Pull request by OverHash**
A lot of this code is messy and has unused variables. Additionally, there are memory leaks as dead entities are not removed from memory.

Fixes some issues related to #964

### CODE REVIEW

**Comment by OverHash** [comment]
This PR still needs work, it needs to be able to listen for
- player movement changes (to see what entities went out of its range as it moved)
- player death (to stop attacking entities)

**Comment by ReinforceZwei** [comment]
Player movement was handled properly, also and the calculation of distance between player and entities.
For player death, you can override `ChatBot.OnHealthUpdate()` method to know player's health. If the health is 0, that mean the player was dead.

**Comment by OverHash** [comment]
Player movement isn't handled properly. If the entities all stay in the same spot, and the player moves back 5 units, it will still continue to attack.

What method can I override to add a callback for player movement?

**Comment by ORelio** [comment]
Hi,

Just pushed a few formatting fixes.
The current state of your PR seems good to me, please let me know when you are ready for merging.

Regarding movement: You can get coordinates using the bot API but there is not event currently when the player is forcefully moved by the server. `GetCurrentLocation()` is supposed to be up to date at the time it is called, i.e. if a new location is received from the server, it will be reflected in the ChatBot API.

**Comment by OverHash** [comment]
Thanks! I'm new to C# so not quite sure what the formatting is.

About to push a commit which should be the last of my changes. Please let me know your thoughts on this.

**Comment by ORelio** [comment]
Seems good! Merged your pull request.

**Pull request merged**
