### PR TITLE
Script to let the bot act like a mail plugin.

### PR DESCRIPTION
**Pull request by Daenges**
This script lets the bot act like a mail plugin. You can send mails through private messaging the bot with "sendmail [Text]". You can configure many options in the option class. If you want to, you can point several instances to one file and create a cross server mail system, with each bot perfectly configured for the individual server.

### CODE REVIEW

**Comment by ORelio** [comment]
Looks cool! Including this into the Modules directory containing optional ChatBots 🙂

**Comment by Daenges** [comment]
Oh I closed something. I'm sorry, I am new at github. Did I delete my code through deleting the branch?

**Comment by Daenges** [comment]
Oh, accidently closed it. Oops.
I reworked the file a bit again. I think i'll upload an updated version soon! Thanks for your compliment, it was hard work and to see it in the project is glad to see!

**Comment by ORelio** [comment]
Actually I already merged it ^^
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config/Modules
But you can submit it again in a new PR

**Comment by Daenges** [comment]
I was already afraid that I delwted everything. But I will do a new request woth the updated version ;D

**Pull request merged**
