### PR TITLE
Added 1.16(.1) support

### PR DESCRIPTION
**Pull request by Bas950**
closes https://github.com/ORelio/Minecraft-Console-Client/issues/1090

### CODE REVIEW

**Comment by ORelio** [comment]
Hi,

Thanks for your contribution.

According to https://wiki.vg/Pre-release_protocol there are new packet IDs and packet layout changes that need to be implemented for 1.16 support to work properly in MCC. You'll need to add new cases for 1.16 in  Protocol18PacketTypes.cs with new IDs and adjust packet decoding/encoding in Protocol18.cs.

Also, I see you updated the following checks:
`if (handler.GetTerrainEnabled() && protocolversion > MC1161Version)`
However, terrain data information such as block palette have not been updated so terrain handling will likely not work.
You could either:
1. Don't update terrain handling yet (just add initial support)
2. Perform full update to terrain handling for 1.16

If you want to perform option 2, see Material.cs and ItemType.cs for updating block and item data inside MCC.

**Comment by Bas950** [comment]
> Hi,
> 
> Thanks for your contribution.
> 
> According to https://wiki.vg/Pre-release_protocol there are new packet IDs and packet layout changes that need to be implemented for 1.16 support to work properly in MCC. You'll need to add new cases for 1.16 in Protocol18PacketTypes.cs with new IDs and adjust packet decoding/encoding in Protocol18.cs.
> 
> Also, I see you updated the following checks:
> `if (handler.GetTerrainEnabled() && protocolversion > MC1161Version)`
> However, terrain data information such as block palette have not been updated so terrain handling will likely not work.
> You could either:
> 
> 1. Don't update terrain handling yet (just add initial support)
> 2. Perform full update to terrain handling for 1.16
> 
> If you want to perform option 2, see Material.cs and ItemType.cs for updating block and item data inside MCC.

Oh ye sorry I just looked at how you guys did 1.15.1 and 1.15.2 :/ 
Will take a look at it later I guess

**Comment by ORelio** [comment]
Yeah, no worries. For minor versions, just marking as supported usually works, but major versions are quite more involved.

**Comment by Bas950** [comment]
@ORelio 
First of, sorry for the commit messages xD, I accidently pressed revert..

> According to https://wiki.vg/Pre-release_protocol there are new packet IDs and packet layout changes that need to be implemented for 1.16 support to work properly in MCC.

That should be done now, there were a few packets that weren't listed on that page, so I guess they weren't changed.

> You'll need to add new cases for 1.16 in Protocol18PacketTypes.cs with new IDs and adjust packet decoding/encoding in Protocol18.cs.

Don't know what to do here tbh.

> Also, I see you updated the following checks:
`if (handler.GetTerrainEnabled() && protocolversion > MC1161Version)`
However, terrain data information such as block palette have not been updated so terrain handling will likely not work.

I reverted that.

**Comment by ORelio** [comment]
That's fine, I'll squash them into a single commit. The IDs look great, I think you're done here 👍
After checking packet differences for adjusting packet decoding/encoding, seems like the following packets need changes:
 - Join Game : [MCC](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L216), [Wiki](https://wiki.vg/Pre-release_protocol#Join_Game)
 - Respawn : [MCC](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L251), [Wiki](https://wiki.vg/Pre-release_protocol#Respawn)

Since terrain, inventories and entities will be turned off for now, these are the only packets that need change for basic chat support to work. Since packet layout has changed, new checks need to be done in order to decode them properly for 1.16 while keeping backwards support for other protocol versions.

Remark: the `Identifier` data type [seems to be a string](https://wiki.vg/Protocol#Identifier) so `dataTypes.ReadNextString(packetData);` should be able to skip them.

**Comment by Bas950** [comment]
Sorry that it says there are many changing in my latest commit @ORelio my Prettier VSCode extension kicked in it looks like :/
Nothing was really changed just the spacing.

> After checking packet differences for adjusting packet decoding/encoding, seems like the following packets need changes:

Join Game : MCC, Wiki
Respawn : MCC, Wiki

that should be fixed now.

> Remark: the Identifier data type seems to be a string so dataTypes.ReadNextString(packetData); should be able to skip them.

Thanks for that. 1 thing tho I added readNextVarIntArray and I used noticed it should be string array, will fix it in a bit, or should readNextString work for it?

**Comment by Bas950** [comment]
> 1 thing tho I added readNextVarIntArray and I used noticed it should be string array, will fix it in a bit, or should readNextString work for it?

Please test it since I am not able to atm, but I just used ReadNextString

**Comment by Bas950** [comment]
> my Prettier VSCode extension kicked in it looks like :/
Nothing was changed by it just the spacing.

You could disable this or add the custom settings with a prettier config file.

**Comment by ORelio** [comment]
I think you can change you indentation level in your settings from 2 spaces to 4 spaces in order to fix that.

**Comment by ORelio** [comment]
Thanks, after a few fixes it's good to go and tested working. 👍

**Pull request merged**
