### PR TITLE
Fix some minor bugs

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Fix spider not considered as hostile mob
Fix crafting result slot not being handled correctly
Added new ChatBot event OnInventoryUpdate

### CODE REVIEW

**Comment by Nekiplay** [comment]
BotLoad(new AutoCarft()); 

There is no such bot in your Pull Request

**Comment by ReinforceZwei** [comment]
@Nekiplay Oops, my bad. I forgot to remove it before committing. Thanks for your remind!

**Comment by ReinforceZwei** [comment]
Fixed. 
_Please note that I have reset and force pushed this branch._

**Comment by Nekiplay** [comment]
Could you add the OnInvenoryOpen Event

**Comment by ORelio** [comment]
Looks good 👍

**Pull request merged**
