### PR TITLE
Implement Microsoft account login

### LINKED ISSUE #1286: Dinnerbone announcing migrating Mojang accs to Microsoft
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

**Description of the Questions**
Title. https://www.youtube.com/watch?v=i9cqIwrgz7w

That would be complex to implement Microsoft auth as that would require a browser authentification I think :cries:

### LINKED ISSUE #1379: Mojang/Microsoft Account Transition
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Good evening,

Mojang will be migrating its existing accounts to Microsoft accounts in the near future. I wanted to pose the question to you on whether Minecraft Console Client will support the new accounts after the migration. Thank you for your time.

### PR DESCRIPTION
**Pull request by ReinforceZwei**
Resolve #1379 
Resolve #1286

### CODE REVIEW

**Comment by ReinforceZwei** [comment]
I didn't take the proxy into consideration when implementing this.

**Comment by ORelio** [comment]
Thanks @ReinforceZwei for working on this, I'll have a look for the proxy thing before merging.

**Comment by ORelio** [comment]
```C#
session = new SessionToken() { ClientID = Guid.NewGuid().ToString().Replace("-", "") }; // <- What is this?
```
Seems like a random UUID without hyphens (`-`)

**Comment by ReinforceZwei** [comment]
> Thanks @ReinforceZwei for working on this, I'll have a look for the proxy thing before merging.

@ORelio  I am implementing the proxy.

**Comment by ORelio** [comment]
> @ORelio I am implementing the proxy and almost done.

Oh. Ok, I was just getting started so I'll let you finish.

**Comment by ReinforceZwei** [comment]
Maybe I need some help. I am creating a http request class by using raw tcp connection and I cannot make cookie to work.

**Comment by ReinforceZwei** [comment]
I don't have any proxy for testing. Some free proxy server on the Internet doesn't work either. I will assume it work because it uses the same API as `ProtocolHandler.DoHTTPSRequest()` to get the proxied tcp client.

**Comment by ORelio** [comment]
It should work indeed as long as you use the TCP client given by the proxy class. It makes no differences between proxy on and proxy off once the connection is established correctly. I remember writing more advanced HTTP requests in the past including reading chunked responses and putting everything into this class: [HttpRawRequest.cs](https://github.com/ORelio/Sharp-Tools/blob/master/Network/HTTPRawRequest.cs).

**Comment by ReinforceZwei** [comment]
I have finished the work on this PR. Please make a review.

**Comment by ORelio** [comment]
Good to hear, was about to ask you about this 👍

**Comment by ORelio** [comment]
Thanks for your work! I'll merge the PR.

FYI it seems like when typing the login and password interactively, the client does not ask if the account is a microsoft account or a mojang account. But it I understand it well, Mojang accounts [will be disabled soon anyway](https://www.minecraft.net/en-us/article/java-edition-moving-house) so no need to implement that, the only account type will be Microsoft soon.

**Comment by ORelio** [comment]
Also, as your pull requests are almost always readily OK for merging and you've been working on MCC for many months, I'm adding you to the repository so that you can directly commit without PRs if you feel comfortable with that. Of course you can still open PRs if you wish to discuss some commits before merging.

**Comment by ORelio** [comment]
@TheSnoozer Speaking about direct access to the MCC repository, do you still need access?

**Comment by TheSnoozer** [comment]
Hi @ORelio, thanks for checking in. To be honest I somewhat has grown more interest in other projects and somewhat moved away from minecraft. As a result feel free to remove my direct access to the MCC repository. Personally I could still contribute (via MRs) so it doesn't feel I lost anything to be honest. Besides hat I think it's a great call to give @ReinforceZwei the permissions to merge here directly.

**Comment by TNTUP** [comment]
Is has been tested? As soon the migration starts I'd be happy to use MCC with MSA accounts!! I'm so happy right now :D

**Comment by ReinforceZwei** [comment]
@TNTUP It has been tested and working great.

**Comment by TNTUP** [comment]
> @TNTUP It has been tested and working great.

Great!! <3 Thank you so much for this PR!!

**Comment by ORelio** [comment]
@TheSnoozer OK, no worries. I'm removing the access for now but you can still create pull requests and I'll add access back if needed. To be honest, I'm having less time for MCC myself and haven't played Minecraft for years but fortunately the project has gained two active contributors lately, @ReinforceZwei and @Nekiplay, who worked hard to add new features such as inventories, entities, ability to place/break blocks, support for new versions and a bunch of new chatbot APIs 👏

**Pull request merged**
