### PR TITLE
Replay

### PR DESCRIPTION
**Pull request by ReinforceZwei**
From #1007

image
_30k+ addition lines only for zip file support Orz_

Improvement 
- [x] Auto-save the recording in case the client crashed or force closed 
- [x] Handle unexpected client disconnect 
- [x] Commands for stop recording and save replay without exiting the program

### CODE REVIEW

**Comment by ReinforceZwei** [comment]
Improvement done. Ready for review.

**Comment by Nekiplay** [comment]
It seems to me better to put most of this in a script and add a link to the DLL Ionic.Zip

**Comment by Nekiplay** [comment]
"selfId" It seems to me that it should be equal to the Entity ID of the local player, you have -1 since you most likely took the metadata from the local world record

**Comment by ReinforceZwei** [comment]
> "selfId" It seems to me that it should be equal to the Entity ID of the local player, you have -1 since you most likely took the metadata from the local world record

No, I do all my stuff on a server not single player world.

**Comment by Nekiplay** [comment]
> > "selfId" It seems to me that it should be equal to the Entity ID of the local player, you have -1 since you most likely took the metadata from the local world record
> 
> No, I do all my stuff on a server not single player world.
At the moment I'm trying to figure out how to play the file through mod

**Comment by Nekiplay** [comment]
Mod file
image
MCC File
image

**Comment by Nekiplay** [comment]
> > > "selfId" It seems to me that it should be equal to the Entity ID of the local player, you have -1 since you most likely took the metadata from the local world record
> > 
> > 
> > No, I do all my stuff on a server not single player world.
> > At the moment I'm trying to figure out how to play the file through mod

Fixed in change fileFormatversion from 14 to 9
image

**Review by ORelio — APPROVED** [review]
Thanks for your hard work on implementing support for Replay capture files! 👍
(Also sorry for the delay in reviewing your PR)

**Pull request merged**
