### PR TITLE
RunScript

### PR DESCRIPTION
**Pull request by Nekiplay**
### Done

- [x] RunScript(ChatBot bot)

### CODE REVIEW

**Comment by ReinforceZwei** [comment]
Not sure why would you copy my work to your own pull request. They don't even have any conflict.

**Comment by ReinforceZwei** [comment]
Please delete your commits that copied from my work.

**Comment by Nekiplay** [comment]
> Please delete your commits that copied from my work.

Okay

**Comment by ORelio** [comment]
@ReinforceZwei's changes still appear after merging #1107 so the pull request now contains conflicts. The change is rather small so I added it manually as `BotLoad(...` instead of `RunScript(...` since it's for loading a ChatBot not a script 😉

**Pull request closed without merging**
