### PR TITLE
Add lock to chatlog file

### LINKED ISSUE #1484: Sharing violation - Chatlog
Every few hours the bot keeps spamming Errors in the cinsole which say (shortened):
Sharing violation on path [path of chatlog] 
at MCC.Chatbot. ChatLog

In my understanding that would mean that another program tries to use the same file on the same time or something about similar. But I dont think there is so it must have to do with a problen coming from MCC. Do you know what is wrong?
Thanks

### PR DESCRIPTION
**Pull request by ReinforceZwei**
try to resolve #1484

### CODE REVIEW

**Comment by ORelio** [comment]
I think the issue is caused by having multiple MinecraftClient.exe trying to access the same lock file. Unless the user wants to load multiple ChatLog bots into the same MinecraftClient.exe writing to a single log file, having this kind of lock will have no effect.

There is a FileMonitor class for handling concurrency, although it does not have a method for appending text yet:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/FileMonitor.cs

**Comment by ReinforceZwei** [comment]
Wouldn't it be the thread-safe issue like the one in web access, executing command cause client to crash?

**Comment by ORelio** [comment]
You can do both internal lock and retry on write just to be safe. Internal lock ensures thread safety within a process and retries ensure proper writing when several processes want to write to the same file.

**Comment by ORelio** [comment]
(although I'm not sure why someone would want to log different accounts to the same log file)

**Review by ORelio — APPROVED** [review]
It can't hurt to have a lock file here. OK with this PR 👍

**Pull request merged**
