### PR TITLE
Effects list & OnScoreboardObjective event & OnEntityEffect event & OnUpdateScore event & EntityInteract (Right Click) & Hand list

### PR DESCRIPTION
**Pull request by Nekiplay**
### `Done ✅` 
- [x] Effects list enum `✔`
- [x] Hand list enum `✔`
- [x] OnEntityEffect event `✔`
- [x] OnScoreboardObjective event `✔`
- [x] OnUpdateScore event `(Entity name is not displayed correctly) ✖`
- [x] EntityInteract `(Right Click) ✔`
- [x] GetEntities() in ChatBots `(Dictionary<int, Entity>) ✔` 
- [x] UpdateCommandBlock `✔`
### `Checked for bugs ⚠`
- [x] Work 1.11 - 1.15.2 `All ✔`
- [x] Work 1.8 - 1.15.2 `OnScoreboardObjective, OnUpdateScore ✔` & `Due to the fact that older versions do not support Entity Handling, not all new features are supported ✖`
### `Pull request 👍`
- [x] Done `Checked for compilation errors & Checked for client errors`
### `Information and presentation of ideas ❄`
If you want to help me with ideas, come to the streams [YouTube](https://www.youtube.com/c/Nekiplay) or my [VK ✉](https://vk.com/neki_play)

### CODE REVIEW

**Comment by ORelio** [comment]
Thanks for your contribution. Seems like your fork does not include the latest commits such as 8b208c5520180a5f4fa194e58c2146d2e93e169e so you might need to sync it. 😉

**Comment by Nekiplay** [comment]
> Thanks for your contribution. Seems like your fork does not include the latest commits such as [8b208c5](https://github.com/ORelio/Minecraft-Console-Client/commit/8b208c5520180a5f4fa194e58c2146d2e93e169e) so you might need to sync it. 😉

It seems to have added everything

**Comment by Nekiplay** [comment]
> Thanks for your contribution. Seems like your fork does not include the latest commits such as [8b208c5](https://github.com/ORelio/Minecraft-Console-Client/commit/8b208c5520180a5f4fa194e58c2146d2e93e169e) so you might need to sync it. 😉

Glad to help, I love Minecraft and have been playing it for over 9 years and I like learning something new and helping )

**Comment by ORelio** [comment]
Thanks. I see that you removed the limit on smallTeleport, please note that larger teleports will be rejected by the server anyway.

**Pull request merged**
